### ISSUE TITLE
SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.

### ISSUE THREAD

**Issue by MiguelQueiroz** [bitrise-steplib/steps-certificate-and-profile-installer#57]
Hello guys,

i'm waiting hours and hours, i cannot figure out how to make this work.
I have the secret env with the certificate passkey in place i know its correct

![image](https://user-images.githubusercontent.com/2479868/80546766-7183cf80-89ae-11ea-825b-45d5597fab3b.png)

And i get this in the log:

![image](https://user-images.githubusercontent.com/2479868/80546867-a6902200-89ae-11ea-9c1a-9c3e04bd6846.png)

Also the red circled paths im not settings,  believe they are automatic right?

![image](https://user-images.githubusercontent.com/2479868/80546949-e48d4600-89ae-11ea-854b-ca53bbea1abb.png)

Any help?

**Comment by MiguelQueiroz** [comment]
Now it works, i removed and added the certificate again, and then set the password.. strange..

**Comment by bitce** [comment]
Hi @MiguelQueiroz! Sorry to hear about this experience, but really glad to hear it started working. For urgent help in the future, please consider reaching out to Support directly on-site :)
