### ISSUE TITLE
Ability turn off debug/info logs

### ISSUE THREAD

**Issue by keremgund** [bitrise-steplib/steps-certificate-and-profile-installer#58]
At the moment there is no option to set log level.
We're experiencing huge bitrise build log files and one of the reasons is this step prints all available certificates/prov profiles, device UUIDs etc which we can't control to not print.
So if you add option quiet (similar on xcodebuild) to allow us see only warning/error messages it would be great.

Thanks,
Kerem

**Comment by bitce** [comment]
Thanks for the feature request @keremgund!
