### ISSUE TITLE
Using a vertical bar (|) as a password for a distribution certificate will result in a failure.

### ISSUE THREAD

**Issue by srea** [bitrise-steplib/steps-certificate-and-profile-installer#59]
If a vertical bar is used as the password for the distribution certificate, the number after the split does not match in the following part, and an error occurs

https://github.com/bitrise-steplib/steps-certificate-and-profile-installer/blob/2bba6a2304ffd0abfdf440d79b1e4fa261a31517/main.go#L356-L357

https://github.com/bitrise-steplib/steps-certificate-and-profile-installer/blob/2bba6a2304ffd0abfdf440d79b1e4fa261a31517/main.go#L359-L361

I think I need to inform Bitrise users that including the vertical bar in the password of the distribution certificate will not work properly.

ex) `&Gxa8G|a^tg` -> `&Gxa8G` `a^tg`

**Comment by mjones-droid** [comment]
Thank you for reporting this. I've filed a bug report with the developers.
