### ISSUE TITLE
Failed to parse certificate

### ISSUE THREAD

**Issue by rokgregoric** [bitrise-steplib/steps-certificate-and-profile-installer#60]
Failed to parse certificate, error: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:63 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2

**Comment by wilcopots** [comment]
Same issue here!

**Comment by devitito** [comment]
Same here!

**Comment by chaitanyatanna-bitrise** [comment]
Hello,
Can you please share more information regarding the issue?
Could you enable Support Access and send the build URL?

Thanks
Chaitanya

**Comment by rokgregoric** [comment]
Its fixed already.

Rok

skype: rokgregoric
twitter: @rokgregoric
linkedin.com/in/rokgregoric

**Comment by chaitanyatanna-bitrise** [comment]
Thank you for the update @rokgregoric 

Chaitanya
