### ISSUE TITLE
Step is not working on Xcode 13.3

### ISSUE THREAD

**Issue by w3ggy** [bitrise-steplib/steps-certificate-and-profile-installer#76]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is affected? 1.10.4
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Issue description

The step is not working on the latest stack with Xcode 13.3 included. Downgrading to 13.2 solves the problem. I even removed all my own certificates but the step still fails with the prebuilt Bitrise certificate. I use all default settings for this step. Looks like a problem within this step itself.

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: NO_
- Log: 

<details>
  <pre>
Downloading certificate: 1/1
Installing downloaded certificates
iPhone Developer: Dev Portal Bot Bitrise (E89JV3W9K4)
serial: 149308669917794252413558859495036042076
team: BITFALL FEJLESZTO KORLATOLT FELELOSSEGU TARSASAG (72SA8V3WYL)
expire: 2022-04-16 12:26:25 +0000 UTC
security "set-key-partition-list" "-S" "apple-tool:,apple:" "-k" "[REDACTED]" "/Users/[REDACTED]/Library/Keychains/login.keychain" failed, out: security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
keychain: "/Users/[REDACTED]/Library/Keychains/login.keychain-db"
version: 512
class: 0x0000000F 
  </pre>
</details>

### Steps to reproduce

1. Use this step
2. Select stack with `Xcode 13.3`
3. The error happens

**Comment by TimYusR** [comment]
Have the same issue

**Comment by lpusok** [comment]
Hello @w3ggy @TimYusR,
We are investigating the issue.
The Xcode version on 13.3 Stack is still Beta 1, will resolve it in a new Stack or Step release.

**Comment by shams-ahmed** [comment]
In the meantime please downgrade to Xcode 13.2

**Comment by alexverbitsky** [comment]
same here

**Comment by yuukiw00w** [comment]
Have same issue.
Xcode 13.3 has been officially released, so it is need to fix as soon as possible.

**Comment by ofalvai** [comment]
Hey everyone! We have released a few stack updates since this issue was opened, and in our own tests the step is working on the Xcode 13.3 stack.

Please let us know if you still have trouble with this step + stack combination, but in the meantime, I'm closing this issue.
